### ISSUE TITLE
TypeError: Cannot read property 'chartVisibility' of undefined

### ISSUE THREAD

**Issue by dragonjet** [RafalWilinski/express-status-monitor#100]
NodeJS `6.11.1`
Amazon Elastic Beanstalk `Node.js running on 64bit Amazon Linux/4.2.1`
package.json: `"express-status-monitor": "^1.0.0",`

Errors in our production services.
This used to work on our previous deployments. (1.0.0)
This happened on latest publish of `express-status-monitor` (1.1.0)

```
TypeError: Cannot read property 'chartVisibility' of undefined
    at Object.keys.reduce (/var/app/current/node_modules/express-status-monitor/src/middleware-wrapper.js:12:15)
    at Array.reduce (native)
    at middlewareWrapper (/var/app/current/node_modules/express-status-monitor/src/middleware-wrapper.js:11:68)
    at Object.<anonymous> (/var/app/current/src/routes/system.js:17:50)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by RafalWilinski** [comment]
Fix published, resolved
