### ISSUE TITLE
Error in latest release

### ISSUE THREAD

**Issue by fedebertolini** [RafalWilinski/express-status-monitor#105]
hi @RafalWilinski, the latest release 1.2.0 seems to have an issue with a missing module.
In this PR https://github.com/RafalWilinski/express-status-monitor/pull/104/, in `src/middleware-wrapper.js` an import to `handlebars` was added but the dependency was not added to the package.json.

We started getting this error:
```
2018-09-18_11:57:27.50571 Error: Cannot find module 'handlebars'
2018-09-18_11:57:27.50580     at Function.Module._resolveFilename (module.js:476:15)
2018-09-18_11:57:27.50589     at Function.Module._load (module.js:424:25)
2018-09-18_11:57:27.50597     at Module.require (module.js:504:17)
2018-09-18_11:57:27.50602     at require (internal/module.js:20:19)
2018-09-18_11:57:27.50608     at Object.<anonymous> (/src/my-app/node_modules/express-status-monitor/src/middleware-wrapper.js:4:20)
```

**Comment by fedebertolini** [comment]
Update: this problem might only affect applications using npm 3 and 4. That PR added a package-lock file, and I see the `handlebars` dependency there.

**Comment by fedebertolini** [comment]
I created a PR adding the missing dependency: https://github.com/RafalWilinski/express-status-monitor/pull/106
