### ISSUE TITLE
error in health-checker.js

### ISSUE THREAD

**Issue by mgautam98** [RafalWilinski/express-status-monitor#107]
I npm installed express-status-monitor. When I try to run my application It is throwing following error

/home/ubuntu/workspace/node_modules/express-status-monitor/src/helpers/health-checker.js:5
module.exports = async (healthChecks) => {
                                       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/express-status-monitor/src/middleware-wrapper.js:8:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

Can you tell me how to fix this.

**Comment by RafalWilinski** [comment]
What Node.js version are you using?

**Comment by mgautam98** [comment]
v6.11.2

**Comment by mgautam98** [comment]
I update the node version to 8.12.0 and now its working.
