### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by hiagodotme** [RafalWilinski/express-status-monitor#113]
When creating a new node js project, if I add the express-status-monitor package and configure it I get the error below.

```
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at c:\Users\hiago\Documents\Development\ld\api\node_modules\request-promise-native\lib\rp.js:8:12
    at module.exports (c:\Users\hiago\Documents\Development\ld\api\node_modules\stealthy-require\lib\index.js:62:23)
    at Object.<anonymous> (c:\Users\hiago\Documents\Development\ld\api\node_modules\request-promise-native\lib\rp.js:7:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

To solve the problem I installed the request in my main application. But I do not use this package, the correct is `express-status-monitor` having the` request` in its dependencies? Or the `request-promise-native` fix that?

**Comment by percenuage** [comment]
Yes this project need `request` as dependency because `request-promise-native` has 

> request is defined as a peer-dependency and thus has to be installed separately.

**Comment by YasharF** [comment]
Can this issue be closed?  It looks like request is now listed as one of the dependencies.
