### ISSUE TITLE
Deprecated 'port' config is needed

### ISSUE THREAD

**Issue by idanielsteven** [RafalWilinski/express-status-monitor#17]
PORT config is needed especially when running two servers in the same container. Port conflicts occur otherwise. 

NodeJS 4.4.7 on Ubuntu Trusty/64-140.4

Error: listen EADDRINUSE :::41338
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)

**Comment by idanielsteven** [comment]
I was on 0.0.6 from  yesterdays install. Tried 0.0.9 and it seems to work fine now.
