### ISSUE TITLE
Error: 27676 does not exist at ChildProcess

### ISSUE THREAD

**Issue by starsoccer** [RafalWilinski/express-status-monitor#49]
Not sure if this is a pidusage or a express-status-monitor problem, but when running nodejs I will sometimes(seemingly randomly) get multiple errors that show have the same number error. It appears as  follows,

Error: 27676 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by mattiaerre** [comment]
maybe @soyuka can help here? are you on Windows I guess right?

// cc @RafalWilinski

**Comment by starsoccer** [comment]
Yes I am on windows 10

**Comment by soyuka** [comment]
Yes it's windows. @starsoccer have a way to reproduce? I'd be interested in such a case. It's wmic not returning any result when the spawn stream closes.

**Comment by starsoccer** [comment]
@soyuka well I have only been running it on windows and have not gotten a way to reproduce it, but basically when running nodejs it will normally occur within a min or two from when I start it. I will try to reproduce it and compare the error and see if it changes at all though.

**Comment by soyuka** [comment]
Thing is I've no windows to test this :|. It comes from [that line](https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L151), the best would be to fork pidusage and to log stderr on every call.

**Comment by starsoccer** [comment]
hmm okay, I did some more testing on my side. I cant seem to consistently make it occur, but when it does occur its some random process ID followed by the same 6 line error. It typically happens 5 or 6 times as well.

So when it occurs, I get 5 or 6 errors each are identical errors with the same process ID.

Not sure if that helps at all though.

**Comment by soyuka** [comment]
did you log [stderr](https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L153)? If the process is alive it's weird that `wmic` doesn't return anything, I'll try to investigate.

**Comment by starsoccer** [comment]
I added console.log(stderr) right before stderr = stderr.trim() and waited for the error to occur. When it finally did occur, the console was printing quite a bit so I paused visual studio and copy/pasted some of it below starting at the top. Some of the errors appear to be new. Let me know if this helps at all.

Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)

Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)



Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)


Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)

Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)



Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)



Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Error: 15016 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)

**Comment by soyuka** [comment]
This is the error you get from the callback, you have to log `stderr` '[~l149](https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L149)

**Comment by starsoccer** [comment]
To clarify, I do not have it reproducible, just If I wait long enough it seems to happen.

I moved console.log(stderr); to be right abouve the if(!stdout) below is what I get:

Node - ComputerNameHere
ERROR:
Description = Out of memory

Error: 25812 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I have checked my computer and my memory is barely 40% in use.

**Comment by soyuka** [comment]
Thanks this helps! I'll look for a solution 😠

**Comment by soyuka** [comment]
I've upgraded pidusage to use raw data instead of formatted ones. This should speed up the pidusage call and maybe fix your error! Just waiting for tests to pass before I publish the patch. In the mean time you can try the master branch: https://github.com/soyuka/pidusage.

**Comment by starsoccer** [comment]
Thanks, though I honestly have no idea where/how to start in order to use the master branch for express-status-monitor.

If its easy to do, you can try to walk me through it, otherwise I can just wait a few days for it or you can ping me when its ready.

**Comment by soyuka** [comment]
I published a patch, it should be available by reinstalling the `express-status-monitor` package (command `npm update`). To check if pidusage is `1.0.5`, you can locate the package.json at `express-status-monitor/node_modules/pidusage/package.json`.

**Comment by starsoccer** [comment]
Just updated it and confirmed its using PIDusage 1.0.5. When running it below is the errors I get

No Instance(s) Available.

Error: 26136 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:493:12)
Node - COMPUTERNAMEHERE
ERROR:
Description = Not enough storage is available to complete this operation.

Error: 26136 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Node - COMPUTERNAMEHERE
ERROR:
Description = Out of memory

Error: 26136 does not exist
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:151:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by soyuka** [comment]
wtf npm publish took the old version, may you update again (will be 1.0.6)? You should get more data in the logs and wmic should take less memory.

**Comment by starsoccer** [comment]
I just tried updating, still only getting 1.0.5

**Comment by soyuka** [comment]
An alternative is to do `npm install pidusage@1.0.6`

**Comment by starsoccer** [comment]
Yes, but doing so will cause express-status-monitor to still use 1.0.5. In any case I still have not been able to pull the latest version.

I will try again later today and tomorrow.

**Comment by starsoccer** [comment]
No luck pulling 1.0.6

**Comment by soyuka** [comment]
```
git clone git@github.com:RafalWilinski/express-status-monitor
cd express-status-monitor
npm install
npm ls | grep pidusage
├── pidusage@1.0.6
```

Delete your node_modules directory and install again. You may also clear the cache `npm cache clear -f`

**Comment by yoanmarchal** [comment]
no more errors on windows 10 since i manually update pidusage@1.0.4 to pidusage@1.0.6 in nodemodules/express-status-monitor/package.json

**Comment by soyuka** [comment]
Great news!!! Thank you very much for testing this!

**Comment by starsoccer** [comment]
I have managed to update it to 1.0.6 sadly this did not resolve the error for me. Below is the new error I am getting:

Error: Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Wmic reported the following error: Node - COMPUTERNAMEHERE
ERROR:
Description = Unspecified error
Invalid XML content..
 Wmic exited with code 44213.
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:159:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Wmic reported the following error: No Instance(s) Available..
 Wmic exited with code 0.
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:159:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Wmic reported the following error: Node - COMPUTER NAME HERE
ERROR:
Description = Out of memory.
 Wmic exited with code 2147749894.
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:159:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Wmic reported the following error: No Instance(s) Available..
 Wmic exited with code 0.
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:159:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Wmic reported the following error: No Instance(s) Available..
 Wmic exited with code 0.
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:159:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Wmic reported the following error: No Instance(s) Available..
 Wmic exited with code 0.
    at ChildProcess.<anonymous> (\node_modules\pidusage\lib\stats.js:159:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by soyuka** [comment]
Thanks, indeed I've more informations in those errors :).

So, first you've this weird error `Description = Unspecified error Invalid XML content..` which I can not explain.

Then, about `Description = Out of memory.` please try to apply [this hotfix](https://support.microsoft.com/en-us/kb/981314).

When it says `No Instance(s) Available..`, wmic can not find your process id. Either the service is stopped, either it's windows doing weird things and I can not find the cause (maybe related to the out of memory thing).

Either way, I'm not able to reproduce the issue on appveyor. I added the launched command to the error, you may want to update pidusage to `1.0.7` if you want even more detailed logs.

**Comment by starsoccer** [comment]
Is there anyway to log what the XML content is?

That hotfix looks to only apply to windows 7 and not windows 10.

I am not finding pidusage 1.0.7 yet but I will check again later today and update to it.

**Comment by soyuka** [comment]
Nope, apparently, this is because the `wmic` xml parser got an invalid result. I don't know if there is a `wmic` log somewhere but it might be where to look for more data. Anyway, according to the [wmi error code reference](https://msdn.microsoft.com/en-us/library/aa394559(v=vs.85).aspx):

> WBEM_E_OUT_OF_MEMORY
2147749894 (0x80041006)
Not enough memory for the operation.

**Comment by starsoccer** [comment]
I am not at all familar with WMI or WBEM so both mean very little to me. I can confirm task manager shows only 44% of my ram in use.

**Comment by soyuka** [comment]
Yeah I believe you but I don't know if WMI has limits on itself. Anyway, if it only stop working after few iterations, this means wmi has a leak somewhere... I would've used powershell if I could but it can't work without an attached terminal (which means that a window would popup every time we launch `pidusage.stat`. I'm trying to increase the use of wmi on appveyor to reproduce.

**Comment by starsoccer** [comment]
I am not sure what you mean by a few interations, but typically the first minute or two it is fine. Then the errors start to appear. Typically once that happens I close it, but if I wait long enough the errors do seem to eventually stop. I am not sure if they will start back up again or not though

**Comment by soyuka** [comment]
Yeah, few iterations means calling `wmic` every `X` seconds for 10 minutes. 

> but if I wait long enough the errors do seem to eventually stop

This would mean that `wmi` eventually get it's memory back? I'm trying to find things that could help but there aren't much on the subject :/, maybe I should start using `bing` for more luck 😼

**Comment by RafalWilinski** [comment]
Is this actionable anyhow? Am I correct that it's dependency + specific OS issue?

**Comment by soyuka** [comment]
It's only a Windows issue. Might be random though, we should see if anyone
else has the same issue. What's the interval used to trigger pidusage?

From what I understood you can reproduce by letting the script run for ~10
minutes+.

**Comment by starsoccer** [comment]
Well typically it happens to me within 5 mins at least one. It will usually spew 30-50 errors of the same thing and then stop. I can try to let it run for an hour and see if it spews anything useful.

**Comment by RafalWilinski** [comment]
I'm planning to add option to exclude some charts/data from plugin. This should mitigate this error in some cases.

**Comment by soyuka** [comment]
Can you explain why you need `spans`? Those are spawning lots of `pidusage.stat()`.

For example, having stats every seconds, if you need those every 10 seconds too, you might just split the first data-set every 10?

**Comment by soyuka** [comment]
ping would love an answer about spans

**Comment by starsoccer** [comment]
After updating PIDusage and express-status-monitor, my errors seems to have gone away. I will play with it a bit more, but for now, the issue seems to be resolved.

**Comment by soyuka** [comment]
:) nice to know thanks for those reports !

**Comment by starsoccer** [comment]
No problem, I will stress test it a bit more over the weekend and see if I get any new errors. If I do you will be the first to know ;)

**Comment by soyuka** [comment]
Please install pidusage@1.1.0 I made an upgrade today should work even
better ;)

**Comment by starsoccer** [comment]
Already on it!
